### ISSUE TITLE
Extreme Lag

### ISSUE THREAD

**Issue by JoelHannemann** [minttuNB/ppcat#2]
Opening the Program twice makes it basically impossible to move the mouse (You have to use ALT+TAB to get to PPCat window and ALT+F4 it to somehow gain control again)

**Comment by minttuNB** [comment]
I feel like it might be because of the not-so-good way of doing the wave animation at the beginning.
Try commenting out the highlighted lines
![image](https://user-images.githubusercontent.com/22272913/45652434-9136ee80-bb0f-11e8-9309-1882ad7a604b.png)  
in this file https://github.com/minttuNB/ppcat/blob/master/renderer.js and see if it fixes it.
My lack of animating skills comes back to bite me ¯\\\_(ツ)_/¯

**Comment by JoelHannemann** [comment]
I've changed it up to skip the waving and immediately boot from start(); (of course adding the keyboard images back in though), but this still occurs. Maybe it's the mouse tracking?

**Comment by JoelHannemann** [comment]
No problem, mate. Good job on the app though

**Comment by minttuNB** [comment]
Fixed here https://github.com/minttuNB/ppcat/commit/9fe33c83664612c64ec44b856315e8473946efd0 , to be added in the 1.1.0 release.
